export const brands = [
	"ASUS",
	"Acer",
	"Apple",
	"Dell",
	"HP",
];
export const sellers = [
	"Rozetka",
	"Others",
];
export const products = [
	{
		id: 1,
		name: "І'мя1",
		brand: "Apple",
		seller: "Rozetka",
		description: "Характеристики товару і т. д.",
		price: 25999,
		link: "#someLink",
	},
	{
		id: 2,
		name: "І'мя2",
		brand: "ASUS",
		seller: "Rozetka",
		description: "Характеристики товару і т. д.",
		price: 25999,
		link: "#someLink",
	},
	{
		id: 3,
		name: "І'мя3",
		brand: "Acer",
		seller: "Others",
		description: "Характеристики товару і т. д.",
		price: 25999,
		link: "#someLink",
	},
	{
		id: 4,
		name: "І'мя4",
		brand: "Acer",
		seller: "Others",
		description: "Характеристики товару і т. д.",
		price: 25999,
		link: "#someLink",
	},
	{
		id: 5,
		name: "І'мя5",
		brand: "Dell",
		seller: "Others",
		description: "Характеристики товару і т. д.",
		price: 25999,
		link: "#someLink",
	},
	{
		id: 6,
		name: "І'мя6",
		brand: "Dell",
		seller: "Rozetka",
		description: "Характеристики товару і т. д.",
		price: 25999,
		link: "#someLink",
	},
	{
		id: 7,
		name: "І'мя7",
		brand: "HP",
		seller: "Rozetka",
		description: "Характеристики товару і т. д.",
		price: 25999,
		link: "#someLink",
	},
	{
		id: 8,
		name: "І'мя8",
		brand: "HP",
		seller: "Rozetka",
		description: "Характеристики товару і т. д.",
		price: 25999,
		link: "#someLink",
	},
	{
		id: 9,
		name: "І'мя9",
		brand: "Dell",
		seller: "Others",
		description: "Характеристики товару і т. д.",
		price: 25999,
		link: "#someLink",
	},
]